
import type { Post } from './types';
import { Timestamp } from 'firebase/firestore';
import type { WeatherForecast } from '@/ai/flows/get-weather-forecast';

// Helper to create a Firestore Timestamp from a Date
const toTimestamp = (date: Date): Timestamp => {
  return new Timestamp(date.getTime() / 1000, 0);
};

export const mockPosts: Post[] = [
  // Lifestyle Articles (10)
  {
    id: 'lifestyle-1',
    title: 'The Rise of Mindful Escapism: Finding Balance in a Busy World',
    slug: 'mindful-escapism-balance',
    content: 'Exploring how Kenyans are embracing mindful practices and local travel to find tranquility and balance amidst the hustle and bustle of modern life. From yoga retreats in Watamu to silent hikes in the Aberdares.',
    coverImage: 'https://picsum.photos/seed/lifestyle-1/1200/800',
    tags: ['Lifestyle', 'Wellness', 'Travel'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-20T10:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-20T10:00:00Z')),
  },
  {
    id: 'lifestyle-2',
    title: 'Nairobi\'s Culinary Renaissance: A Taste of the City\'s Best',
    slug: 'nairobi-culinary-renaissance',
    content: 'From gourmet burgers to authentic Ethiopian platters, Nairobi\'s food scene is exploding with flavor. We take you on a culinary tour of the city\'s most talked-about restaurants and hidden gems.',
    coverImage: 'https://picsum.photos/seed/lifestyle-2/1200/800',
    tags: ['Lifestyle', 'Food', 'Nairobi'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-19T12:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-19T12:00:00Z')),
  },
  {
    id: 'lifestyle-3',
    title: 'The Art of Kitenge: Modern Twists on a Classic Fabric',
    slug: 'kitenge-modern-twists',
    content: 'Kitenge is more than just a fabric; it\'s a statement. See how local designers are reimagining this traditional textile into contemporary fashion pieces that are taking the world by storm.',
    coverImage: 'https://picsum.photos/seed/lifestyle-3/1200/800',
    tags: ['Lifestyle', 'Fashion', 'Culture'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-18T15:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-18T15:00:00Z')),
  },
  {
    id: 'lifestyle-4',
    title: 'Weekend Getaway Guide: Uncovering the Magic of Naivasha',
    slug: 'naivasha-weekend-getaway',
    content: 'Lake Naivasha offers the perfect escape from the city. Here’s our guide to the best activities, from boat rides to see hippos to hiking in Hell\'s Gate National Park.',
    coverImage: 'https://picsum.photos/seed/lifestyle-4/1200/800',
    tags: ['Lifestyle', 'Travel', 'Kenya'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-17T11:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-17T11:00:00Z')),
  },
  {
    id: 'lifestyle-5',
    title: 'Homegrown Harmony: The Rise of Kenyan Indie Music',
    slug: 'kenyan-indie-music-rise',
    content: 'A new wave of independent artists is redefining the Kenyan music scene. Discover the sounds and stories of the musicians creating the soundtrack for a new generation.',
    coverImage: 'https://picsum.photos/seed/lifestyle-5/1200/800',
    tags: ['Lifestyle', 'Music', 'Culture'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-16T18:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-16T18:00:00Z')),
  },
  {
    id: 'lifestyle-6',
    title: 'Interior Design Trends: Incorporating African Art into Modern Homes',
    slug: 'african-art-interior-design',
    content: 'Learn how to blend traditional African art, sculptures, and textiles into your modern living space to create a home that is both stylish and culturally rich.',
    coverImage: 'https://picsum.photos/seed/lifestyle-6/1200/800',
    tags: ['Lifestyle', 'Home Decor', 'Art'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-15T09:30:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-15T09:30:00Z')),
  },
  {
    id: 'lifestyle-7',
    title: 'The Thriving Coffee Culture in the Heart of Kenya',
    slug: 'kenyan-coffee-culture',
    content: 'Kenya is famous for its coffee beans, and now a vibrant cafe culture is brewing. We explore the best spots to enjoy a perfectly crafted cup of Kenyan coffee.',
    coverImage: 'https://picsum.photos/seed/lifestyle-7/1200/800',
    tags: ['Lifestyle', 'Food', 'Nairobi'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-14T14:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-14T14:00:00Z')),
  },
  {
    id: 'lifestyle-8',
    title: 'Fitness in the City: Nairobi\'s Best Running and Cycling Routes',
    slug: 'nairobi-fitness-routes',
    content: 'Staying active in a bustling city can be a challenge. We map out the safest and most scenic routes for running and cycling in and around Nairobi.',
    coverImage: 'https://picsum.photos/seed/lifestyle-8/1200/800',
    tags: ['Lifestyle', 'Fitness', 'Nairobi'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-13T16:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-13T16:00:00Z')),
  },
  {
    id: 'lifestyle-9',
    title: 'A Literary Journey: The Bookstores and Libraries Championing Kenyan Authors',
    slug: 'kenyan-literary-scene',
    content: 'Discover the spaces nurturing Kenya\'s literary talent. From cozy independent bookstores to community libraries, these are the places where stories come to life.',
    coverImage: 'https://picsum.photos/seed/lifestyle-9/1200/800',
    tags: ['Lifestyle', 'Culture', 'Literature'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-12T13:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-12T13:00:00Z')),
  },
  {
    id: 'lifestyle-10',
    title: 'The Enduring Appeal of Maasai Markets: A Guide for Shoppers',
    slug: 'maasai-markets-guide',
    content: 'A trip to a Maasai market is a vibrant cultural experience. Our guide helps you navigate the stalls, bargain like a local, and find authentic, handcrafted treasures.',
    coverImage: 'https://picsum.photos/seed/lifestyle-10/1200/800',
    tags: ['Lifestyle', 'Travel', 'Culture'],
    status: 'draft',
    createdAt: toTimestamp(new Date('2024-07-11T10:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-11T10:00:00Z')),
  },

  // Gadgets Articles (10)
  {
    id: 'gadgets-1',
    title: 'The Best Budget Smartphones in Kenya for 2024',
    slug: 'best-budget-smartphones-kenya-2024',
    content: 'Looking for a new phone without breaking the bank? We review the top budget smartphones available in the Kenyan market, focusing on battery life, camera quality, and performance.',
    coverImage: 'https://picsum.photos/seed/gadgets-1/1200/800',
    tags: ['Gadgets', 'Technology', 'Reviews'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-21T09:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-21T09:00:00Z')),
  },
  {
    id: 'gadgets-2',
    title: 'Surviving Power Outages: Top 5 Gadgets for Load Shedding',
    slug: 'top-gadgets-load-shedding',
    content: 'With intermittent power cuts, being prepared is key. We look at essential gadgets, from portable power stations to solar chargers, that will keep your devices running.',
    coverImage: 'https://picsum.photos/seed/gadgets-2/1200/800',
    tags: ['Gadgets', 'Lifestyle', 'Technology'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-20T11:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-20T11:00:00Z')),
  },
  {
    id: 'gadgets-3',
    title: 'The Rise of FinTech: Mobile Payment Apps Revolutionizing Kenya',
    slug: 'fintech-mobile-payment-apps-kenya',
    content: 'Beyond M-Pesa, a new generation of FinTech apps is changing how Kenyans transact. We explore the features and benefits of the most innovative payment solutions.',
    coverImage: 'https://picsum.photos/seed/gadgets-3/1200/800',
    tags: ['Gadgets', 'Technology', 'Business'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-19T14:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-19T14:00:00Z')),
  },
  {
    id: 'gadgets-4',
    title: 'Affordable Laptops for Students and Professionals in Nairobi',
    slug: 'affordable-laptops-nairobi',
    content: 'Whether you\'re a student on a budget or a professional on the go, finding the right laptop is crucial. Here are our top picks for affordable and powerful laptops in 2024.',
    coverImage: 'https://picsum.photos/seed/gadgets-4/1200/800',
    tags: ['Gadgets', 'Technology', 'Reviews'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-18T10:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-18T10:00:00Z')),
  },
  {
    id: 'gadgets-5',
    title: 'Smart Home Technology: Is Kenya Ready for the Connected Home?',
    slug: 'smart-home-tech-kenya',
    content: 'From smart lighting to voice assistants, connected home devices are gaining popularity worldwide. We investigate the adoption and practicality of smart home technology in Kenya.',
    coverImage: 'https://picsum.photos/seed/gadgets-5/1200/800',
    tags: ['Gadgets', 'Technology', 'Lifestyle'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-17T17:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-17T17:00:00Z')),
  },
  {
    id: 'gadgets-6',
    title: 'The Ultimate Guide to Buying a Second-Hand Smartphone in Kenya',
    slug: 'guide-buying-second-hand-smartphone',
    content: 'Buying a used phone can save you money, but it comes with risks. Our guide tells you what to look for, where to buy, and how to avoid common scams.',
    coverImage: 'https://picsum.photos/seed/gadgets-6/1200/800',
    tags: ['Gadgets', 'Technology', 'Tips'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-16T13:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-16T13:00:00Z')),
  },
  {
    id: 'gadgets-7',
    title: 'Gaming in Kenya: The State of PC and Console Gaming',
    slug: 'gaming-in-kenya-2024',
    content: 'The gaming community in Kenya is growing rapidly. We look at the latest trends, the most popular games, and the challenges and opportunities for gamers in the country.',
    coverImage: 'https://picsum.photos/seed/gadgets-7/1200/800',
    tags: ['Gadgets', 'Gaming', 'Culture'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-15T19:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-15T19:00:00Z')),
  },
  {
    id: 'gadgets-8',
    title: 'Wearable Tech Review: The Best Fitness Trackers for Your Workout',
    slug: 'best-fitness-trackers-review',
    content: 'From tracking your steps to monitoring your heart rate, fitness trackers are powerful tools. We test and review the best wearables available in Kenya.',
    coverImage: 'https://picsum.photos/seed/gadgets-8/1200/800',
    tags: ['Gadgets', 'Reviews', 'Fitness'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-14T12:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-14T12:00:00Z')),
  },
  {
    id: 'gadgets-9',
    title: 'The Role of Drones in Kenyan Agriculture and Logistics',
    slug: 'drones-kenyan-agriculture-logistics',
    content: 'Drones are no longer just for photography. They are transforming industries like agriculture and logistics in Kenya. We explore their current and potential impact.',
    coverImage: 'https://picsum.photos/seed/gadgets-9/1200/800',
    tags: ['Gadgets', 'Technology', 'Innovation'],
    status: 'draft',
    createdAt: toTimestamp(new Date('2024-07-13T11:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-13T11:00:00Z')),
  },
  {
    id: 'gadgets-10',
    title: 'Protecting Your Digital Life: Essential Cybersecurity Tips',
    slug: 'essential-cybersecurity-tips',
    content: 'In an increasingly digital world, protecting your personal information is vital. Our experts share practical and essential tips to keep you safe online.',
    coverImage: 'https://picsum.photos/seed/gadgets-10/1200/800',
    tags: ['Gadgets', 'Technology', 'Tips'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-12T15:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-12T15:00:00Z')),
  },

  // Fashion Articles (10)
  {
    id: 'fashion-1',
    title: 'Nairobi Fashion Week: The Bold and the Beautiful',
    slug: 'nairobi-fashion-week-recap',
    content: 'A complete recap of the most stunning looks and groundbreaking designs from this year\'s Nairobi Fashion Week. Discover the designers to watch and the trends that will dominate the scene.',
    coverImage: 'https://picsum.photos/seed/fashion-1/1200/800',
    tags: ['Fashion', 'Nairobi', 'Events'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-22T14:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-22T14:00:00Z')),
  },
  {
    id: 'fashion-2',
    title: 'Sustainable Style: The Kenyan Brands Championing Eco-Fashion',
    slug: 'kenyan-sustainable-fashion-brands',
    content: 'Meet the local fashion brands that are putting sustainability at the heart of their work. From upcycled materials to ethical production, these labels are making a difference.',
    coverImage: 'https://picsum.photos/seed/fashion-2/1200/800',
    tags: ['Fashion', 'Sustainability', 'Lifestyle'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-21T16:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-21T16:00:00Z')),
  },
  {
    id: 'fashion-3',
    title: 'The Modern Man: A Guide to Men\'s Fashion in Kenya',
    slug: 'mens-fashion-guide-kenya',
    content: 'From sharp official wear to casual weekend looks, Kenyan men\'s fashion is evolving. We provide style tips, shopping guides, and inspiration for the modern gentleman.',
    coverImage: 'https://picsum.photos/seed/fashion-3/1200/800',
    tags: ['Fashion', 'Menswear', 'Lifestyle'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-20T13:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-20T13:00:00Z')),
  },
  {
    id: 'fashion-4',
    title: 'Beadwork and Beyond: The Art of Maasai Jewellery',
    slug: 'maasai-jewellery-art',
    content: 'The intricate beadwork of the Maasai people is globally renowned. We delve into the history, symbolism, and contemporary evolution of this beautiful art form.',
    coverImage: 'https://picsum.photos/seed/fashion-4/1200/800',
    tags: ['Fashion', 'Culture', 'Art'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-19T10:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-19T10:00:00Z')),
  },
  {
    id: 'fashion-5',
    title: 'How to Style Ankara Prints for Any Occasion',
    slug: 'how-to-style-ankara-prints',
    content: 'Ankara prints are versatile and vibrant. Learn how to style them for the office, a wedding, or a casual day out with our expert tips and lookbook.',
    coverImage: 'https://picsum.photos/seed/fashion-5/1200/800',
    tags: ['Fashion', 'Lifestyle', 'Tips'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-18T18:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-18T18:00:00Z')),
  },
  {
    id: 'fashion-6',
    title: 'The Best Thrift Shopping Spots in Nairobi',
    slug: 'best-thrift-spots-nairobi',
    content: 'Thrifting, or "mutumba," is a huge part of Kenyan style. We uncover the best markets and hidden spots in Nairobi to find unique and affordable fashion gems.',
    coverImage: 'https://picsum.photos/seed/fashion-6/1200/800',
    tags: ['Fashion', 'Lifestyle', 'Nairobi'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-17T14:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-17T14:00:00Z')),
  },
  {
    id: 'fashion-7',
    title: 'Kenyan Wedding Gowns: A Blend of Tradition and Modernity',
    slug: 'kenyan-wedding-gown-trends',
    content: 'Today\'s Kenyan brides are embracing gowns that fuse traditional elements with contemporary designs. Explore the latest trends in bridal wear.',
    coverImage: 'https://picsum.photos/seed/fashion-7/1200/800',
    tags: ['Fashion', 'Weddings', 'Culture'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-16T11:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-16T11:00:00Z')),
  },
  {
    id: 'fashion-8',
    title: 'Accessory Spotlight: The Rise of Handcrafted Leather Goods',
    slug: 'kenyan-leather-goods',
    content: 'From bags to sandals, Kenyan artisans are creating world-class leather goods. We highlight the brands and workshops producing high-quality, handcrafted pieces.',
    coverImage: 'https://picsum.photos/seed/fashion-8/1200/800',
    tags: ['Fashion', 'Artisans', 'Lifestyle'],
    status: 'draft',
    createdAt: toTimestamp(new Date('2024-07-15T16:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-15T16:00:00Z')),
  },
  {
    id: 'fashion-9',
    title: 'Street Style: What the Cool Kids of Nairobi Are Wearing',
    slug: 'nairobi-street-style',
    content: 'We hit the streets of Nairobi to capture the most creative and inspiring looks. Get a glimpse into the city\'s vibrant and eclectic street style scene.',
    coverImage: 'https://picsum.photos/seed/fashion-9/1200/800',
    tags: ['Fashion', 'Street Style', 'Nairobi'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-14T17:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-14T17:00:00Z')),
  },
  {
    id: 'fashion-10',
    title: 'The Evolution of the Kiondo: From Market Bag to High Fashion',
    slug: 'evolution-of-kiondo',
    content: 'The humble kiondo has been transformed into a high-fashion accessory, seen on runways and city streets alike. We trace its journey and celebrate its timeless appeal.',
    coverImage: 'https://picsum.photos/seed/fashion-10/1200/800',
    tags: ['Fashion', 'Culture', 'History'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-13T12:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-13T12:00:00Z')),
  },
   {
    id: 'mock-1',
    title: 'Kenya Launches New Tech Hub in Nairobi to Foster Innovation',
    slug: 'kenya-launches-new-tech-hub-nairobi',
    content: 'The Kenyan government has officially opened a new state-of-the-art technology hub in Nairobi, aimed at fostering innovation and entrepreneurship among the youth. The hub, named "Silicon Savannah," will provide resources, mentorship, and funding opportunities for startups.',
    coverImage: 'https://picsum.photos/seed/tech-hub-kenya/1200/800',
    tags: ['Technology', 'Kenya', 'Innovation'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-22T10:00:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-22T10:00:00Z')),
  },
  {
    id: 'mock-2',
    title: 'The Great Wildebeest Migration: A Spectacle of Nature',
    slug: 'wildebeest-migration-spectacle',
    content: 'The annual wildebeest migration in the Maasai Mara is in full swing, drawing tourists and wildlife enthusiasts from around the globe. This incredible event sees over a million wildebeest, zebras, and gazelles journey across the plains in search of greener pastures.',
    coverImage: 'https://picsum.photos/seed/wildebeest-migration/1200/800',
    tags: ['Tourism', 'Wildlife', 'Maasai Mara'],
    status: 'published',
    createdAt: toTimestamp(new Date('2024-07-21T14:30:00Z')),
    updatedAt: toTimestamp(new Date('2024-07-21T14:30:00Z')),
  },
];

export const mockTrendingTopics: string[] = [
  '#KenyaDecides',
  '#SiliconSavannah',
  '#MagicalKenya',
  '#FinanceBill2024',
  '#GoTusker',
];

export const mockAds = [
  {
    id: 'ad-1',
    title: 'Safari Adventures',
    description: 'Book your dream Kenyan safari today!',
    imageUrl: 'https://picsum.photos/seed/safari-ad/600/600',
    linkUrl: '#',
    alt: 'Giraffe in the wild'
  }
];

export const mockVideos = [
    {
        id: 'video-1',
        title: 'Exploring the Maasai Mara',
        youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
    },
    {
        id: 'video-2',
        title: 'Nairobi City Tour',
        youtubeUrl: 'https://www.youtube.com/watch?v=VIDEO_ID_2'
    }
];

export const mockMarketData = [
    { ticker: 'SCOM', price: 17.50, change: '+0.25' },
    { ticker: 'EQTY', price: 42.00, change: '-0.10' },
    { ticker: 'KCB', price: 35.75, change: '+0.50' },
    { ticker: 'EABL', price: 155.25, change: '-1.00' },
    { ticker: 'BAMB', price: 210.00, change: '+2.50' },
    { ticker: 'NSE', price: 8.90, change: '+0.05' },
];

export const mockWeatherData: WeatherForecast[] = [
    { location: 'Nairobi, Kenya', temperature: '22°C', condition: 'Partly Cloudy', icon: 'Cloud' },
    { location: 'Mombasa, Kenya', temperature: '28°C', condition: 'Sunny', icon: 'Sun' },
    { location: 'Kisumu, Kenya', temperature: '26°C', condition: 'Chance of Rain', icon: 'CloudRain' },
    { location: 'Eldoret, Kenya', temperature: '20°C', condition: 'Cloudy', icon: 'Cloud' },
];
